name: Lint

on:
  pull_request:
  push:
    branches: [main]
    paths: ["**.rs", "**.toml", "**.lock"]

jobs:
  rust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@main

      - run: nix develop

      - name: clippy
        run: |
          cargo clippy
          cargo clippy --target wasm32-unknown-unknown --lib
          cargo clippy --target wasm32-unknown-unknown --lib --all-features

      - name: rustfmt check
        run: |
          cargo fmt --all --check
